# Terraform Provider testing workflow.
name: Test HA (Trusted)

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
    push:
        branches:
            - main
        paths-ignore:
            - 'CHANGELOG.md'
            - 'README.md'
    workflow_run:
      workflows: ["Test (Untrusted)"]
      types: [completed]
    workflow_dispatch:
      inputs:
        branch:
          description: 'Branch to run tests against'
          required: true
          default: 'main'
          type: string

env:
    LC_APPLICATION_ID: terraform-provider-sonatyperepo
    NEXUS_SECURITY_RANDOMPASSWORD: "false"
    INSTALL4J_ADD_VM_PARAMS: "-Dnexus.licenseFile=${{ github.workspace }}/license.lic"

# Testing only needs permissions to read the repository contents.
permissions:
    contents: read

jobs:
    
    # Run acceptance tests in a matrix with Terraform CLI versions
    test-parallel:
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.ref_name != 'main' && github.event.workflow_run.head_repository.full_name == github.repository) }}
        name: Acc. Tests (NXRM HA ${{ matrix.nxrm }} + TF ${{ matrix.terraform }})
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            fail-fast: false
            matrix:
                nxrm:
                    - '3.89.1-02' # LATEST
                terraform:
                    - '1.14.*' # Latest
        steps:
            - name: Set Clean TF Version
              run: |
                ORIG="${{ matrix.terraform }}"
                TF_SAFE_VERSION="${ORIG//\*/}"
                echo "TF_SAFE_VERSION=$TF_SAFE_VERSION" >> "$GITHUB_ENV"
                
            - name: Checkout Source
              uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5
              with:
                ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

            - name: Setup PostgreSQL
              id: setup-postgresql
              uses: ikalnytskyi/action-setup-postgres@c4dda34aae1c821e3a771b68b73b13af3198a7ee # v8
              with:
                postgres-version: 17
            
            - name: Create database
              run: |
                psql -c "CREATE USER nexus WITH PASSWORD 'somepassword';"
                psql -c "CREATE DATABASE nexus OWNER nexus ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TEMPLATE template0;"
                psql -d nexus -c "CREATE SCHEMA nexus AUTHORIZATION nexus;"
                psql -d nexus -c "GRANT ALL PRIVILEGES ON DATABASE nexus TO nexus; GRANT ALL PRIVILEGES ON SCHEMA nexus TO nexus;"
                psql -d nexus -c "CREATE EXTENSION pg_trgm SCHEMA nexus;"
              env:
                PGSERVICE: ${{ steps.setup-postgresql.outputs.service-name }}

            - name: Download, Unpack & Configure Sonatype Nexus Repository Manager
              run: |
                wget https://download.sonatype.com/nexus/3/nexus-${{ matrix.nxrm }}-linux-x86_64.tar.gz 
                mkdir -p ${{ github.workspace }}/node-01
                mkdir -p ${{ github.workspace }}/node-02
                mkdir -p ${{ github.workspace }}/node-03
                echo "${{ secrets.NXRM_LICENSE }}" | base64 -d > ${{ github.workspace }}/license.lic
                tar xvz --keep-directory-symlink -f nexus-${{ matrix.nxrm }}-linux-x86_64.tar.gz -C ${{ github.workspace }}/node-01
                tar xvz --keep-directory-symlink -f nexus-${{ matrix.nxrm }}-linux-x86_64.tar.gz -C ${{ github.workspace }}/node-02
                tar xvz --keep-directory-symlink -f nexus-${{ matrix.nxrm }}-linux-x86_64.tar.gz -C ${{ github.workspace }}/node-03
                sed -i '1s/^.*$/#!\/bin\/bash/' ${{ github.workspace }}/node-01/nexus-${{ matrix.nxrm }}/bin/nexus
                sed -i '1s/^.*$/#!\/bin\/bash/' ${{ github.workspace }}/node-02/nexus-${{ matrix.nxrm }}/bin/nexus
                sed -i '1s/^.*$/#!\/bin\/bash/' ${{ github.workspace }}/node-03/nexus-${{ matrix.nxrm }}/bin/nexus
                echo "username=nexus" > ${{ github.workspace }}/nexus-store.properties
                echo "password=somepassword" >> ${{ github.workspace }}/nexus-store.properties
                echo "jdbcUrl=jdbc:postgresql://localhost/nexus" >> ${{ github.workspace }}/nexus-store.properties
                mkdir -p ${{ github.workspace }}/node-01/sonatype-work/nexus3/etc/fabric
                mkdir -p ${{ github.workspace }}/node-02/sonatype-work/nexus3/etc/fabric
                mkdir -p ${{ github.workspace }}/node-03/sonatype-work/nexus3/etc/fabric
                echo "application-port=8082" > ${{ github.workspace }}/node-02/sonatype-work/nexus3/etc/nexus-default.properties
                echo "application-port=8083" > ${{ github.workspace }}/node-03/sonatype-work/nexus3/etc/nexus-default.properties
                cp ${{ github.workspace }}/nexus-store.properties ${{ github.workspace }}/node-01/sonatype-work/nexus3/etc/fabric/nexus-store.properties
                cp ${{ github.workspace }}/nexus-store.properties ${{ github.workspace }}/node-02/sonatype-work/nexus3/etc/fabric/nexus-store.properties
                cp ${{ github.workspace }}/nexus-store.properties ${{ github.workspace }}/node-03/sonatype-work/nexus3/etc/fabric/nexus-store.properties

            - name: Start Sonatype Nexus Repository Manager (Node 1)
              run: ./nexus start
              working-directory: "${{ github.workspace }}/node-01/nexus-${{ matrix.nxrm }}/bin"

            - name: Wait for Sonatype Nexus Repository Manager (Node 1) to be ready
              run: |
                  set +e
                  sleep 20
                  while true; do
                    STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8081/service/rest/v1/status")
                    CURL_EXIT=$?

                    echo "CURL Exit Code: $CURL_EXIT"

                    if [ "$CURL_EXIT" -eq 0 ]; then
                      if [ "$STATUS" -eq 200 ]; then
                          echo "✅ Received 200 OK from http://localhost:8081/service/rest/v1/status"
                          break
                      else
                          echo "⏳ Waiting for 200 OK... Current status: $STATUS for http://localhost:8081/service/rest/v1/status"
                          sleep 5
                      fi
                    else
                      echo "⚠️ curl returned unexpected exit code $CURL_EXIT. Retrying..."
                      sleep 5
                    fi
                  done

            - name: Start Sonatype Nexus Repository Manager (Node 2)
              run: ./nexus start
              working-directory: "${{ github.workspace }}/node-02/nexus-${{ matrix.nxrm }}/bin"

            - name: Wait for Sonatype Nexus Repository Manager (Node 2) to be ready
              run: |
                  set +e
                  sleep 20
                  while true; do
                    STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8082/service/rest/v1/status")
                    CURL_EXIT=$?

                    echo "CURL Exit Code: $CURL_EXIT"

                    if [ "$CURL_EXIT" -eq 0 ]; then
                      if [ "$STATUS" -eq 200 ]; then
                          echo "✅ Received 200 OK from http://localhost:8082/service/rest/v1/status"
                          break
                      else
                          echo "⏳ Waiting for 200 OK... Current status: $STATUS for http://localhost:8082/service/rest/v1/status"
                          sleep 5
                      fi
                    else
                      echo "⚠️ curl returned unexpected exit code $CURL_EXIT. Retrying..."
                      sleep 5
                    fi
                  done

            - name: Start Sonatype Nexus Repository Manager (Node 3)
              run: ./nexus start
              working-directory: "${{ github.workspace }}/node-03/nexus-${{ matrix.nxrm }}/bin"

            - name: Wait for Sonatype Nexus Repository Manager (Node 3) to be ready
              run: |
                  set +e
                  sleep 20
                  while true; do
                    STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8083/service/rest/v1/status")
                    CURL_EXIT=$?

                    echo "CURL Exit Code: $CURL_EXIT"

                    if [ "$CURL_EXIT" -eq 0 ]; then
                      if [ "$STATUS" -eq 200 ]; then
                          echo "✅ Received 200 OK from http://localhost:8083/service/rest/v1/status"
                          break
                      else
                          echo "⏳ Waiting for 200 OK... Current status: $STATUS for http://localhost:8083/service/rest/v1/status"
                          sleep 5
                      fi
                    else
                      echo "⚠️ curl returned unexpected exit code $CURL_EXIT. Retrying..."
                      sleep 5
                    fi
                  done

            - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
              with:
                  go-version-file: 'go.mod'
                  cache: true

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
              with:
                  terraform_version: ${{ matrix.terraform }}
                  terraform_wrapper: false
            - run: go mod download
            - env:
                  NXRM_SERVER_URL: "http://localhost:8081"
                  NXRM_SERVER_USERNAME: "admin"
                  NXRM_SERVER_PASSWORD: "admin123"
                  NXRM_VERSION: "${{ matrix.nxrm }}"
                  TF_ACC: '1'
                  TF_ACC_SINGLE_HIT: '1'
              run: go test -v -cover ./...
              timeout-minutes: 10

            - name: Store nexus.log (Node 1)
              if: success() || failure()
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                name: "nexus-node-01.log-nxrm-${{ matrix.nxrm }}-terraform-${{ env.TF_SAFE_VERSION }}"
                path: "${{ github.workspace }}/node-01/sonatype-work/nexus3/log/nexus.log"

            - name: Store nexus.log (Node 2)
              if: success() || failure()
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                name: "nexus-node-02.log-nxrm-${{ matrix.nxrm }}-terraform-${{ env.TF_SAFE_VERSION }}"
                path: "${{ github.workspace }}/node-02/sonatype-work/nexus3/log/nexus.log"

            - name: Store nexus.log (Node 3)
              if: success() || failure()
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                name: "nexus-node-03.log-nxrm-${{ matrix.nxrm }}-terraform-${{ env.TF_SAFE_VERSION }}"
                path: "${{ github.workspace }}/node-03/sonatype-work/nexus3/log/nexus.log"